#!/usr/bin/env bash
# Render the Homebrew formula for a published release.
# Usage: homebrew-formula.sh VERSION ASSET_DIR > Formula/radar.rb
# ASSET_DIR holds radar-<os>_<arch>.tar.gz.sha256 for darwin/linux × amd64/arm64,
# exactly as uploaded to the GitHub Release vVERSION.
set -euo pipefail
if (($# != 2)); then
    printf 'Usage: %s VERSION ASSET_DIR\n' "$0" >&2
    exit 2
fi
version=${1#v}
assets=$2
repository=${RADAR_REPOSITORY:-Jake-Network/radar}
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$ ]]; then
    printf 'Invalid version %s.\n' "$version" >&2
    exit 2
fi
checksum() {
    local file="$assets/radar-$1.tar.gz.sha256" digest name extra
    [[ -f "$file" ]] || { printf 'Missing %s.\n' "$file" >&2; exit 1; }
    read -r digest name extra < "$file"
    if [[ ! "$digest" =~ ^[a-f0-9]{64}$ || "$name" != "radar-$1.tar.gz" || -n "${extra:-}" ]]; then
        printf 'Invalid checksum file %s.\n' "$file" >&2
        exit 1
    fi
    printf '%s' "$digest"
}
url="https://github.com/$repository/releases/download/v$version"
cat <<EOF
# Generated by scripts/homebrew-formula.sh for v$version; do not edit by hand.
class Radar < Formula
  desc "Check that parallel coding-agent branches work together before merging"
  homepage "https://github.com/$repository"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$url/radar-darwin_arm64.tar.gz"
      sha256 "$(checksum darwin_arm64)"
    end
    on_intel do
      url "$url/radar-darwin_amd64.tar.gz"
      sha256 "$(checksum darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$url/radar-linux_arm64.tar.gz"
      sha256 "$(checksum linux_arm64)"
    end
    on_intel do
      url "$url/radar-linux_amd64.tar.gz"
      sha256 "$(checksum linux_amd64)"
    end
  end

  def install
    bin.install "radar"
    doc.install "README.md", "DEPENDENCIES.txt", "licenses"
    pkgshare.install "integrations", "examples"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/radar version")
    repo = testpath/"repo"
    system "git", "init", "-q", "-b", "main", repo.to_s
    (repo/"app.py").write "def run():\n    return 1\n"
    git = ["git", "-C", repo.to_s, "-c", "user.name=Radar", "-c", "user.email=radar@example.invalid"]
    system(*git, "add", ".")
    system(*git, "commit", "-qm", "baseline")
    system(*git, "branch", "feature")
    assert_match "Radar gate", shell_output("#{bin}/radar gate --root #{repo} feature")
  end
end
EOF
